// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/1/19 18:07:36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/salween.li/my proj/SalweenBlog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salween.li/my proj/SalweenBlog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salween.li/my proj/SalweenBlog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salween.li/my proj/SalweenBlog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salween.li/my proj/SalweenBlog/plugins/**/*.{js,ts,mjs}","/Users/salween.li/my proj/SalweenBlog/composables/**/*.{js,ts,mjs}","/Users/salween.li/my proj/SalweenBlog/utils/**/*.{js,ts,mjs}","/Users/salween.li/my proj/SalweenBlog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/salween.li/my proj/SalweenBlog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/salween.li/my proj/SalweenBlog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/salween.li/my proj/SalweenBlog/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["16"] = "/Users/salween.li/my proj/SalweenBlog/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;